name: mogo
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - brotli-python=1.0.9=py310h6a678d5_8
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.7.2=h06a4308_0
  - certifi=2024.8.30=py310h06a4308_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - cudatoolkit=11.8.0=h6a678d5_0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.13.1=py310h06a4308_0
  - freetype=2.12.1=h4a9f257_0
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py310heeb90bb_0
  - gnutls=3.6.15=he1e5248_0
  - idna=3.7=py310h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jinja2=3.1.4=py310h06a4308_0
  - jpeg=9e=h5eee18b_3
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libdeflate=1.17=h5eee18b_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=2.1.3=py310h5eee18b_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py310h5eee18b_1
  - mkl_fft=1.3.10=py310h5eee18b_0
  - mkl_random=1.2.7=py310h1128e8f_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py310h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.3=py310h06a4308_0
  - numpy=1.26.4=py310h5f9d8c6_0
  - numpy-base=1.26.4=py310hb5e798b_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openssl=3.0.15=h5eee18b_0
  - pip=24.2=py310h06a4308_0
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.14=h955ad1f_1
  - pytorch-mutex=1.0=cpu
  - pyyaml=6.0.1=py310h5eee18b_0
  - readline=8.2=h5eee18b_0
  - sqlite=3.45.3=h5eee18b_0
  - sympy=1.13.2=py310h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.14=h39e8969_0
  - torchaudio=2.1.1=py310_cpu
  - torchvision=0.16.1=py310_cpu
  - typing_extensions=4.11.0=py310h06a4308_0
  - urllib3=2.2.2=py310h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.5=hc292b87_2
  - pip:
      - absl-py==2.1.0
      - accelerate==0.34.2
      - addict==2.4.0
      - aiohappyeyeballs==2.4.0
      - aiohttp==3.10.5
      - aiosignal==1.3.1
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anykeystore==0.2
      - apex==0.9.10.dev0
      - appdirs==1.4.4
      - astunparse==1.6.3
      - async-timeout==4.0.3
      - attrs==24.2.0
      - av==11.0.0
      - chardet==5.2.0
      - click==8.1.7
      - cloudpickle==3.0.0
      - colorama==0.4.6
      - contourpy==1.3.0
      - cryptacular==1.6.2
      - cycler==0.12.1
      - dataproperty==1.0.1
      - datasets==2.19.1
      - decord==0.6.0
      - deepspeed==0.13.1
      - defusedxml==0.7.1
      - dill==0.3.8
      - docker-pycreds==0.4.0
      - einops==0.7.0
      - evaluate==0.4.2
      - exceptiongroup==1.2.2
      - flatbuffers==24.3.25
      - fonttools==4.53.1
      - frozenlist==1.4.1
      - fsspec==2024.3.1
      - ftfy==6.1.3
      - fvcore==0.1.5.post20221221
      - gast==0.6.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - google-pasta==0.2.0
      - greenlet==3.0.3
      - grpcio==1.66.1
      - h5py==3.11.0
      - hjson==3.1.0
      - huggingface-hub==0.24.6
      - hupper==1.12.1
      - imageio==2.33.1
      - iniconfig==2.0.0
      - iopath==0.1.10
      - joblib==1.4.2
      - jsonlines==4.0.0
      - keras==3.5.0
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - libclang==18.1.1
      - lightning-utilities==0.11.9
      - lm-eval==0.4.1
      - lxml==5.3.0
      - markdown==3.7
      - markdown-it-py==3.0.0
      - matplotlib==3.9.2
      - mbstrdecoder==1.1.3
      - mdurl==0.1.2
      - ml-dtypes==0.3.2
      - mmcv==2.2.0
      - mmengine==0.10.5
      - multidict==6.0.5
      - multiprocess==0.70.16
      - namex==0.0.8
      - ninja==1.11.1.1
      - nltk==3.9.1
      - numexpr==2.10.1
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.6.68
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.2.2
      - omegaconf==2.3.0
      - opencv-python==4.8.1.78
      - opt-einsum==3.3.0
      - optree==0.12.1
      - packaging==24.0
      - pandas==2.2.1
      - pastedeploy==3.1.0
      - pathvalidate==3.2.1
      - pbkdf2==1.3
      - peft==0.12.0
      - pillow==10.1.0
      - plaster==1.1.2
      - plaster-pastedeploy==1.0.1
      - platformdirs==4.3.6
      - pluggy==1.5.0
      - portalocker==2.10.1
      - protobuf==4.25.4
      - psutil==6.0.0
      - py-cpuinfo==9.0.0
      - pyarrow==17.0.0
      - pyarrow-hotfix==0.6
      - pybind11==2.13.5
      - pycocotools==2.0.8
      - pydantic==2.9.0
      - pydantic-core==2.23.2
      - pygments==2.18.0
      - pynvml==11.5.3
      - pyparsing==3.1.4
      - pyramid==2.0.2
      - pyramid-mailer==0.15.1
      - pytablewriter==1.2.0
      - pytest==8.1.1
      - python-dateutil==2.9.0.post0
      - python3-openid==3.2.0
      - pytz==2024.1
      - regex==2023.10.3
      - repoze-sendmail==4.4.1
      - requests==2.31.0
      - requests-oauthlib==2.0.0
      - rich==13.8.0
      - rouge-score==0.1.2
      - sacrebleu==2.4.3
      - safetensors==0.4.5
      - scikit-image==0.24.0
      - scikit-learn==1.5.1
      - scipy==1.12.0
      - sentry-sdk==2.13.0
      - setproctitle==1.3.3
      - setuptools==68.2.2
      - simplejson==3.19.3
      - six==1.16.0
      - smmap==5.0.1
      - sqlalchemy==2.0.34
      - sqlitedict==2.1.0
      - submitit==1.5.1
      - tabledata==1.3.3
      - tabulate==0.9.0
      - tcolorpy==0.1.6
      - tensorboard==2.16.2
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.2.2
      - tensorflow==2.16.1
      - tensorflow-io-gcs-filesystem==0.37.1
      - termcolor==2.4.0
      - threadpoolctl==3.5.0
      - tifffile==2024.8.30
      - timm==0.4.12
      - tokenizers==0.15.2
      - tomli==2.0.1
      - torch==2.2.0
      - torchinfo==1.8.0
      - torchmetrics==1.6.1
      - tqdm==4.66.1
      - tqdm-multiprocess==0.0.11
      - transaction==4.0
      - transformers==4.36.1
      - translationstring==1.4
      - triton==2.2.0
      - typepy==1.3.2
      - tzdata==2024.1
      - velruse==1.1.1
      - venusian==3.1.0
      - wandb==0.16.2
      - wcwidth==0.2.13
      - webob==1.8.8
      - werkzeug==3.0.4
      - wheel==0.42.0
      - wrapt==1.16.0
      - wtforms==3.1.2
      - wtforms-recaptcha==0.3.2
      - xformers==0.0.24
      - xxhash==3.5.0
      - yacs==0.1.8
      - yapf==0.43.0
      - yarl==1.9.11
      - zope-deprecation==5.0
      - zope-interface==7.0.3
      - zope-sqlalchemy==3.1
      - zstandard==0.23.0
